- .github/workflows/main.yml
Используем токен для возможности пробить защищенную ветку
> ci(main): use DEVTOOLS_GITHUB_TOKEN

- .github/workflows/main.yml
> ci(main): fix secret

- vkui-tokens/token-base/src/main.ts
Добавляем в выходной json форматирование
> fix(token-base): json stringify use 2 space

- VKUI/patch/action.yml
- VKUI/patch/src/main.ts
- VKUI/patch/src/message.ts
Добавляем свойства targetBranch и needScreenshots
> feat(VKUI patch): targetBranch and needScreenshots

- VKUI/patch/src/getBooleanInput.ts
- VKUI/patch/src/main.ts
Исправленная версия getBooleanInput функции из `@actions/core`
- https://github.com/actions/toolkit/issues/844
> fix(VKUI patch): getBooleanInput fix required

- VKUI/complete-publish/src/workflowHandler.ts
> fix(complete-publish): fix issues state

- VKUI/complete-publish/src/workflowHandler.ts
> fix(complete-publish): ignore not planned issues

- VKUI/complete-publish/package.json
- VKUI/patch/package.json
- VKUI/push-screenshots/package.json
- VKUI/reporter/package.json
- VKUI/s3/package.json
- VKUI/stable-branch/package.json
- package.json
- vkui-tokens/token-base/package.json
- yarn.lock
Заменил `ncc` на `esbuild`
<sup><sub>hyperfine --setup 'yarn' --prepare 'git checkout main' 'yarn build # ncc' --prepare 'git checkout SevereCloud/feat/esbuild' 'yarn build # esbuild'</sub></sup>
> feat: esbuild

- VKUI/complete-publish/src/workflowHandler.ts
Добавляем скрытый комментарий для фильтрации уведомлений
> feat(VKUI): complete-publish disable_global_notification

- vkui-tokens/token-base/src/main.ts
- vkui-tokens/token-base/src/sort.ts
Добавляем сортировку ключей в объекте
> fix(token-base): sort object recursively

- shared/download-workflow-artifact/action.yml
Breaking Change: node.js v20
https://github.com/actions/github-script/releases/tag/v7.0.0
> feat: update actions/github-script@v7

- shared/rust/cargo-update-pr/action.yml
> feat: update actions/checkout@v4

- shared/rust/cargo-cache/action.yml
Breaking Change -- обновление node до v20
https://github.com/actions/cache/releases/tag/v4.0.0
> feat: update actions/cache@v4

- VKUI/auto-update-release-notes/src/parsing/convertChangesToString.ts
- VKUI/auto-update-release-notes/src/parsing/getPullRequestReleaseNotesBody.ts
- VKUI/auto-update-release-notes/src/parsing/parseChanges.ts
- VKUI/auto-update-release-notes/src/updateReleaseNotes.test.ts
Сейчас есть баг, что при обновлении релиз ноутов доп информация по пунктам удаляется из списка
- Поправил баг с удалением доп информации по пунктам списка
- Поправил баг с лишним пустым пунктом
> fix: fix parse and update additional info

- VKUI/s3/package.json
- VKUI/s3/src/main.ts
- yarn.lock
Добавляем ограничение на параллельную загрузку файлов
> fix(s3): add maxParallelUploadFiles

- shared/node/corepack-up-pr/action.yml
Добавляем экшон для автоматического обновления версии пакетного менеджера через corepack
> feat: add corepack up pr

- shared/node/nvmrc-up-pr/action.yml
Создает PR при появлении новой версии Node.js обновляя `.nvmrc`
> feat: add Node.js up PR

- VKUI/s3/src/main.ts
Уменьшаем maxConcurrentUploadFiles до 2
> fix(s3): maxConcurrentUploadFiles 2

- VKUI/s3/src/main.ts
Пробуем асинхронную обертку для putObject
> fix: async wrapper for putObject

- VKUI/s3/package.json
- VKUI/size-upload/package.json
- yarn.lock
> Revert "build(deps): bump @aws-sdk/client-s3 from 3.705.0 to 3.712.0"

- .github/workflows/monday.yml
Добавляем автоматическое создание PR-а на обновление Node.js
> ci(monday): add nvmrc-up-pr

- package.json
- shared/spell-checker-filename/.eslintrc.js
- shared/spell-checker-filename/action.yml
- shared/spell-checker-filename/jest.config.ts
- shared/spell-checker-filename/package.json
- shared/spell-checker-filename/src/entities/repositories.ts
- shared/spell-checker-filename/src/main.ts
- shared/spell-checker-filename/src/repositories/github.ts
- shared/spell-checker-filename/src/repositories/spell.test.ts
- shared/spell-checker-filename/src/repositories/spell.ts
- shared/spell-checker-filename/src/service/action.test.ts
- shared/spell-checker-filename/src/service/action.ts
- shared/spell-checker-filename/src/service/service.ts
- shared/spell-checker-filename/tsconfig.json
- yarn.lock
Добавляем экшон для проверки названий файлов. Если есть проблемы выдает предупреждение в PR-е
Требуется для
- https://github.com/VKCOM/icons/issues/770
> feat: add spell-checker-filename

- .github/workflows/main.yml
- .github/workflows/pull_request.yml
- Добавляем проверку зависимостей и кэш
> ci: check dependencies

- VKUI/s3/src/main.ts
- see [aws-sdk-js-v3#6810](https://github.com/aws/aws-sdk-js-v3/issues/6810)
> fix(S3): disable check sum

- VKUI/auto-update-release-notes/src/parsing/convertChangesToString.ts
- VKUI/auto-update-release-notes/src/parsing/parseChanges.ts
- VKUI/auto-update-release-notes/src/parsing/parsePullRequestReleaseNotesBody.ts
- VKUI/auto-update-release-notes/src/parsing/releaseNotesUpdater.ts
- VKUI/auto-update-release-notes/src/types.ts
- VKUI/auto-update-release-notes/src/updateReleaseNotes.test.ts
- VKUI/auto-update-release-notes/src/updateReleaseNotes.ts
Сейчас у релиз ноутов где-то описание начинается со строчной буквы, а где-то с заглавной. А также некоторые описания заканчиваются точкой, а некоторые нет.
- Сделал небольшой рефакторинг парсинга релиз ноутов, добавил парсинг `prNumber` и автора
- Добавил логику выставления заглавной первой буквы в описании и убирание точки из конца
- Доработал тесты
> tech: add changes description formatting

- VKUI/auto-update-release-notes/src/parsing/convertChangesToString.ts
- VKUI/auto-update-release-notes/src/parsing/getComponentDocsUrl.ts
- VKUI/auto-update-release-notes/src/updateReleaseNotes.test.ts
Нужно поменять ссылку на доку компонента
> tech: fix component url in documentation
