- VKUI/patch/src/message.ts
- У `checkout` нет флага `--no-commit`
- glob pattern не должен быть завёрнут в кавычки
> fix(@actions-internal/patch): edit message

- .github/dependabot.yml
- [Configuration options for the dependabot.yml file • groups](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups)
> dependabot: use 'groups'; set schedule to weekly

- VKUI/patch/src/getMergeData.ts
- VKUI/patch/src/main.ts
- VKUI/patch/src/message.ts
Используем для черри пика `merge_commit_sha` если PR был смержен методов **squash**. Иначе, черри пикаем по коммитам в PR. При этом исключаем мерж коммит.
Используем `git diff --quiet HEAD`, чтобы обойти кейсы, когда попадается коммит только со скриншотами. Из-за `git checkout HEAD **/__image_snapshots__/*.png'` нечего становится коммитить и Git падает с ошибкой.
> fix(@actions-internal/patch): optimize cherry-pick

- VKUI/patch/src/main.ts
Перед cherry-pick'ом squash коммита, фетчим этот коммит с флагом `--depth=2`, чтобы перебить параметр `fetch-depth` у `@actions/checkout`, который по умолчанию равен 1.
В https://github.com/VKCOM/VKUI/pull/5465 из-за этого упал CI на `patch`. В нём как раз экшен пытался черри-пикнуть сквош коммит https://github.com/VKCOM/VKUI/commit/095c314f27551541f072df4bf5dc168af496948d, но упал из-за мерж конфликта.
`@actions/checkout` инициализирует воркфлоу так:
```sh
git fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +095c314f27551541f072df4bf5dc168af496948d:refs/remotes/origin/master
```
На стороне `@actions-internal/patch` мы дополнительно фетчим стабильную ветку и коммит
```sh
git fetch --no-tags origin 5.6-stable 095c314f27551541f072df4bf5dc168af496948d
```
но это …
> fix(@actions-internal/patch): fetch with depth=2

- VKUI/patch/dist/index.js
- VKUI/patch/src/main.ts
Use `git format-patch` to prepare the filtered diff on fly and pass it to the `git am`.
This simulate the git `cherry-pick` and allows us to filter out screenshots.
Seems like `git am` doesn't throw an error if the diff is empty we pass to it is empty.
Filtration with `git diff` won't work here as we would loose the commit message.
By default `git format-patch` creates files with diff those can be read by `git am`.
To avoid file creation I use `pipe` to send output of `git format-patch` to `git am`.
Unfortunately `action/exec` can't simulate this `git format-patch ... | git am` with it's interface.
The workaround is to use `/bin/bash -c "comand"`. 
Tested on my fork of [VKUI](https://github.com/mendrew/VKUI).
For tests I used:
- commit …
> Filter out snapshots from squash diff

- VKUI/reporter/action.yml
- VKUI/reporter/src/comment.ts
- VKUI/reporter/src/main.ts
- VKUI/reporter/src/playwrightReport.ts
`github.context.payload.pull_request` не всегда может быть доступен, например, если экшен запустили через `workflow_run`. Поэтому нужна возможность прокидывать номер PR через входные параметры.
> feat(VKUI/reporter): add prNumber input

- shared/download-workflow-artifact/action.yml
Экшен позволяет вытаскивать опр-ый артефакт из другого воркфлоу. Использует [actions/github-script](https://github.com/actions/github-script). Основан на примере из доки [Использование данных из рабочего процесса, активирующего триггер](https://docs.github.com/ru/actions/using-workflows/events-that-trigger-workflows#using-data-from-the-triggering-workflow).
[actions/download-artifact@v3](https://github.com/actions/download-artifact/tree/v3) не умеет в такое (см. issue [actions/download-artifact#3](https://togithub.com/actions/download-artifact/issues/3)).
> **Note**
> Есть альтернатива [dawidd6/action-download-artifact](https://github.com/dawidd6/action-download-artifact), но этот экшен не верифицированный. Пробовал запросить у @VKCOM/vk-sec, но чёт там дело замялось. Да и выяснил, что …
> feat: add shared/download-workflow-artifact

- VKUI/complete-publish/action.yml
- VKUI/complete-publish/src/main.ts
- VKUI/complete-publish/src/workflowHandler.ts
Добавляем поддержку тега `latest`, на случай, если потребуется выпускать релизы не к текущей мажорной верии
> feat(complete-publish): add latest tag processing

- VKUI/complete-publish/action.yml
- VKUI/patch/action.yml
- VKUI/push-screenshots/action.yml
- VKUI/reporter/action.yml
- VKUI/s3/action.yml
- VKUI/stable-branch/action.yml
- vkui-tokens/token-base/action.yml
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
> feat: using node 20

- VKUI/complete-publish/src/workflowHandler.ts
При публикации [v6](https://github.com/VKCOM/VKUI/actions/runs/7543985854) для VKUI не смогли полностью закрыть `milestone`, потому что попалась [issue](https://github.com/VKCOM/VKUI/issues/2684), которая была конвертирована в дискуссию.
Решение: фильтруем по полю `locked` дополнительно, чтобы не пытаться писать в закрытые от обсуждений `issue`.
> fix: Ignore issues with locked discussions

- package.json
- shared/rust/cargo-update-toml/.eslintrc.js
- shared/rust/cargo-update-toml/action.yml
- shared/rust/cargo-update-toml/jest.config.ts
- shared/rust/cargo-update-toml/package.json
- shared/rust/cargo-update-toml/src/getLastLine.test.ts
- shared/rust/cargo-update-toml/src/getLastLine.ts
- shared/rust/cargo-update-toml/src/main.ts
- shared/rust/cargo-update-toml/src/registry.test.ts
- shared/rust/cargo-update-toml/src/registry.ts
- shared/rust/cargo-update-toml/src/versionStyle.test.ts
- shared/rust/cargo-update-toml/src/versionStyle.ts
- shared/rust/cargo-update-toml/tsconfig.json
Добавляем пакет, который умеет обновлять зависимости в Cargo.toml
Использование:
```yml
steps:
- name: Update swc_core
uses: VKCOM/gh-actions/shared/rust/cargo-update-toml@main
with:
packages: swc_core
```
> feat: add cargo-update-toml

- VKUI/complete-publish/dist/index.js
- VKUI/complete-publish/package.json
- VKUI/complete-publish/src/workflowHandler.ts
- yarn.lock
Чтобы можно было повторно вызывать `@actions-internal/complete-publish` на один и тот же релиз, проверяем на предмет выполнения каждого из процессов – так будем избегать ошибок, что что-то уже сделано, а тажке избегать дубоирования комментариев в issues.
Также добавил [@octokit/plugin-retry](https://github.com/octokit/plugin-retry.js) ([документация](https://actions-cool.github.io/octokit-rest/en-US/guide/10_retries/)) для автоматических перезапросов при **5xx** ошибках.
При релизе [@vkontakte/vkui@6.1.0](https://github.com/VKCOM/VKUI/releases/tag/v6.1.0) столкнулись с проблемой, что экшен упал при комментировании issues > 26.
_https://github.com/VKCOM/VKUI/actions/runs/9264916551/job/25486081163_
Хотим уметь повторно запускать `@actions-internal/complete-publish` для завершения экшена.
> feat(VKUI/complete-publish): избегаем запуска если не требуется, а также добавляем @octokit/plugin-retry

- shared/rust/cargo-update-pr/action.yml
> - The default values for author and committer have changed. See "What's new" below for details. If you are overriding the default values you will not be affected by this change.
> - On completion, the action now removes the temporary git remote configuration it adds when using push-to-fork. This should not affect you unless you were using the temporary configuration for some other purpose after the action completes.
https://github.com/peter-evans/create-pull-request/blob/main/docs/updating.md#updating-from-v5-to-v6
> feat: update peter-evans/create-pull-request@v6

- VKUI/complete-publish/package.json
- VKUI/patch/package.json
- VKUI/push-screenshots/package.json
- VKUI/reporter/package.json
- VKUI/s3/package.json
- VKUI/size-upload/package.json
- VKUI/stable-branch/package.json
- shared/rust/cargo-update-toml/package.json
- vkui-tokens/token-base/package.json
После мажорного обновление esbuild-а для бандлинга js-а нужен отдельный флаг
- cause #395
> fix: esbuild packages bundle

- package.json
- yarn.lock
Также удалил зависимости `@typescript-eslint/eslint-plugin` и `@typescript-eslint/parser` в пользу поля `"resolutions"`, чтобы избежать их обновления до **>= 8**. `@vkontakte/eslint-plugin` поддерживает парсер версии **^7.0.1**.
---
- caused by #428
> tech: dedupe deps

- VKUI/auto-update-release-notes/action.yml
- VKUI/auto-update-release-notes/src/calculateReleaseVersion.ts
- VKUI/auto-update-release-notes/src/getRelease.ts
- VKUI/auto-update-release-notes/src/getVersion.ts
- VKUI/auto-update-release-notes/src/main.ts
- VKUI/auto-update-release-notes/src/parsing/releaseNotesUpdater.ts
- VKUI/auto-update-release-notes/src/updateReleaseNotes.test.ts
- VKUI/auto-update-release-notes/src/updateReleaseNotes.ts
Сейчас последняя версия библиотеки `VKUI` рассчитывается путем получения версии из `package.json `в пакете `VKUI`.  Это не совсем правильно, так как патчевые изменения не попадают в `package.json`. Поэтому рассчитать следующую версию для PR в скрипте `auto-update-release-notes` не всегда удается корректно. Нужно рассчитывать актуальную версию исходя из последнего опубликованного релиза
- Реализовал расчет актуальной версии VKUI через метод getLatestRelease, который возвращает последний опубликованный релиз. Из названия этого релиза достаем актуальную версию библиотеки
- Доработал тесты для нового поведения
- Убрал из inputs `current_vkui_version`, так этот параметр больше не нужен
> tech: fix getting latest vkui version

- VKUI/auto-update-release-notes/src/checkVKCOMMember.ts
- VKUI/auto-update-release-notes/src/parsing/convertChangesToString.ts
- VKUI/auto-update-release-notes/src/parsing/getPullRequestReleaseNotesBody.ts
- VKUI/auto-update-release-notes/src/parsing/parseChanges.ts
- VKUI/auto-update-release-notes/src/parsing/releaseNotesUpdater.ts
- VKUI/auto-update-release-notes/src/updateReleaseNotes.test.ts
- VKUI/auto-update-release-notes/src/updateReleaseNotes.ts
Сейчас есть проблема, что в body pull request'а перенос строки обозначается через `\r\n`, а в коде рассчитывалось что перенос строки это `\n`. Из-за этого неправильно парсятся release notes и в целом неправильно работает скрипт
- Добавил поддержку переноса строки через `\r\n` в коде, поправил парсинг
- Добавил пару логов для проверки остального функционала
> tech: fix parsing of release notes

- VKUI/auto-update-release-notes/src/parsing/headers.ts
- VKUI/auto-update-release-notes/src/types.ts
Сейчас для списка breaking changes нет поддержки в скрипте автообновления релиз ноутов
Добавил поддержку заголовка `BREAKING CHANGE` в скрипт обновления релиз ноутов
> feat: add breaking change header support

- VKUI/auto-update-release-notes/src/calculateReleaseVersion.ts
- VKUI/auto-update-release-notes/src/getRelease.ts
- VKUI/auto-update-release-notes/src/updateReleaseNotes.test.ts
- VKUI/auto-update-release-notes/src/updateReleaseNotes.ts
Сейчас скрипт автообновления релиз ноутов некорректно работает с кастомными майлстоунам, например `v7.0.0-beta.0`
- Доработал логику расчет названия релиза на основании title майлстоуна
- Добавил тест покрывающий новую логику
> feat: improve calculating releaseName and release version

- VKUI/auto-update-release-notes/src/parsing/convertChangesToString.ts
- VKUI/auto-update-release-notes/src/parsing/parseChanges.ts
- VKUI/auto-update-release-notes/src/types.ts
- VKUI/auto-update-release-notes/src/updateReleaseNotes.test.ts
Сейчас скрипт по автообновлению release notes не поддерживает код в описании изменения. Конкретно кейс:
- Button: какие то изменения
```diff
- Код до изменений
+ Код после изменений
```
В этом кейсе скрипт может воспринять строку `- Код до изменений` как отдельное изменение из-за того, что в начале идет "-"
Доработал скрипт автообновления, так чтобы блоки кода обрабатывались отдельно при этом сохраняя все внутреннее форматирование для удобства пользования
> fix: fix parse release notes with code block info

- VKUI/add-next-minor-milestone/action.yml
Из-за того, что в скрипте add-next-minor-milestone в action.yml быд неправильно указан путь до скрипта, он падал на ci/cd при создании пул реквеста
Поправил путь до скрипта add-next-minor-milestone
> fix: fix path to script

- VKUI/auto-update-release-notes/src/parsing/parseChanges.ts
Сейчас скрипт авто обновления релиз ноутов падает при парсинге изменений типа:
```
- Компонент:
- Изменение 1
- Изменение 2
```
Ошибка в том, что при проходе регуляркой по строке ожидается, что компонент имеет описание, но так не всегда. Нужно добавить проверку
> fix: fix parsing changes with subitems

- VKUI/auto-update-release-notes/src/calculateReleaseVersion.ts
- VKUI/auto-update-release-notes/src/parsing/parseChanges.ts
- VKUI/auto-update-release-notes/src/parsing/releaseNotesUpdater.ts
- VKUI/auto-update-release-notes/src/updateReleaseNotes.test.ts
В скрипте автообновления релиз ноутов поправил две проблемы:
1. Неправильный расчет ссылки на компонент, если версия релиза с суфиксом -beta.{n}. Поправил парсинг и добавил тест
2. Если в пул реквесте после заголовка раздела(Улучшения, Исправления и тд) поставить пробел, то раздел не парсился, так как искалось совпадение со строкой без пробелов. Поправил проверку, добавил trim, чтобы получить строку без пробелов вокруг
> fix: fix bugs and improve code

- VKUI/s3/package.json
- VKUI/size-upload/package.json
- yarn.lock
Снова откатываем до 3.705.0.
<details><summary>Лог</summary>
<p>
```sh
Run VKCOM/gh-actions/VKUI/s3@main
with:
awsAccessKeyId: ***
awsSecretAccessKey: ***
awsBucket: vkui-screenshot
awsEndpoint: https://hb.bizmrg.com
command: upload
commandUploadSrc: styleguide-dist/
commandUploadDist: pull/8171/146605da870698a5b870e[2](https://github.com/VKCOM/VKUI/actions/runs/12884184217/job/35919947815#step:3:2)f714d4[3](https://github.com/VKCOM/VKUI/actions/runs/12884184217/job/35919947815#step:3:3)9ed1d2bf188/styleguide
env:
PR_HEAD_REPOSITORY_FULL_NAME: VKCOM/VKUI
PR_HEAD_BRANCH: e.muhamethanov/775[4](https://github.com/VKCOM/VKUI/actions/runs/12884184217/job/35919947815#step:3:4)/image-filter-prop
PR_HEAD_SHA: 14660[5](https://github.com/VKCOM/VKUI/actions/runs/12884184217/job/35919947815#step:3:5) …
```
> Revert "build(deps): bump @aws-sdk/client-s3 from 3.705.0 to 3.731.1"

- VKUI/s3/src/main.ts
Пробуем добавить `requestTimeout` со значением в `30` секунд (по умолчанию `0` 🤔 )
> fix(S3): add requestTimeout

- shared/node/nvmrc-up-pr/action.yml
Убираем сортировку по дате, так как могут быть выпущены патчи для старых версий. При этом файл уже отсортирован по версиям
> fix(nvmrc-up-pr): rm sort by date

- VKUI/s3/package.json
- VKUI/size-upload/package.json
- yarn.lock
С aws-sk-js-v3 с `v3.7.29` перешли с MD5 на CRC32 (https://github.com/aws/aws-sdk-js-v3/blob/main/supplemental-docs/MD5_FALLBACK.md).
`v3.726.1` для `@aws-sdk/client-s3`взял исходя из https://github.com/aws/aws-sdk-js-v3/blob/v3.728.0/clients/client-s3/package.json.
> build(deps): downgrade @aws-sdk/client-s3 from 3.758.0 to 3.726.1

- icons/auto-update-release-notes/src/getReleaseDraft.ts
Убрал "v" перед версией в названии релиз ноута, чтобы название соответствовало назвнанию тега при релизе
> fix: fix release name
